language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add .php.ini
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist